create SCHEMA Assignment;
create TABLE Assignment.EMP(
    EMP_CODE CHAR(5) PRIMARY KEY,
    EMP_NAME CHAR(20),
    DEPT_CODE CHAR(5),
    DESIG_CODE CHAR(5),
    SEX CHAR(5),
    ADDRESS CHAR(25),
    CITY CHAR(20),
    STATE CHAR(20),
    PIN CHAR(6),
    BASIC NUMERIC,
    IN_DEPT DATE
);
CREATE TABLE Assignment.DESIGNATION(
    DESIG_CODE CHAR(5) PRIMARY KEY,
    DESIG_DESC CHAR(20)
);
CREATE TABLE Assignment.DEPARTMENT(
    DEPT_CODE CHAR(5) PRIMARY KEY,
    DEPT_NAME CHAR(15)
);